### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by zangxx66** [assassingyk/bang-gacha#1]
1. 请上传一下```Background.png```的资源文件  
2. 如果有邦邦的chara_name就好了，用range的形式会增加不必要的网络请求  
3. 建议用异步请求的形式，避免请求时间过长或请求异常把主线程卡住

**Comment by assassingyk** [comment]
`Background.png`加进data里了；

另外这俩问题的话因为写那俩爬虫时本意是线下一次性使用更新图片资源包与卡牌卡池数据用的（类似hoshino自带的爬pcr官方漫画的那个），bot运行起来以后是不执行这俩爬虫的，所以写的时候没有很在意性能或者效率这些……
今后如果更新（如果我没咕的话）是准备改成直接从besdori之类的网站api在线获取数据，也就根本不需要爬虫了，所以也懒得再修了……
